# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Alice' do
	pod 'RealmSwift'
	pod 'DLRadioButton'
	pod 'IQKeyboardManagerSwift'
end

target 'AliceTests' do

end



